services:
  db:
    image: postgres:16-alpine
    networks:
      - backend-nw
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: slnd_admin
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: slnd_db
    ports:
      - "4610:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend-nw
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    networks:
      - frontend-nw
      - backend-nw
    ports:
      - "4600:4600"
    env_file:
      - ./services/api-gateway/.env
    environment:
      - HOST=0.0.0.0
      - ID_SERVICE_URL=http://id-service:4601
      - AI_AGENT_SERVICE_URL=http://ai-agent-service:4602
    depends_on:
      - id-service
      - ai-agent-service

  id-service:
    build:
      context: ./services/id-service
      dockerfile: Dockerfile
    networks:
      - backend-nw
    ports:
      - "4601:4601"
    env_file:
      - ./services/id-service/.env
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL="postgresql://slnd_admin:dev_password@db:5432/slnd_db"
    depends_on:
      - db

  ai-agent-service:
    build:
      context: ./services/ai-agent-service
      dockerfile: Dockerfile
    networks:
      - backend-nw
    ports:
      - "4602:4602"
    env_file:
      - ./services/ai-agent-service/.env
    environment:
      - HOST=0.0.0.0

networks:
  frontend-nw:
    driver: bridge
  backend-nw:
    driver: bridge

volumes:
  postgres_data:
